
create table if not exists public.dashboard_ga4_acquisition_daily (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.dashboard_clients(id) on delete cascade,
  account_id text not null,
  metric_date date not null,
  channel_group text not null,
  source_medium text not null,
  sessions bigint not null default 0 check (sessions >= 0),
  engaged_sessions bigint not null default 0 check (engaged_sessions >= 0),
  new_users bigint not null default 0 check (new_users >= 0),
  views bigint not null default 0 check (views >= 0),
  events bigint not null default 0 check (events >= 0),
  key_events numeric(20,6) not null default 0 check (key_events >= 0),
  ingested_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint dashboard_ga4_acquisition_daily_unique
    unique (client_id, account_id, metric_date, channel_group, source_medium)
);

create index if not exists dashboard_ga4_acquisition_client_date_idx
  on public.dashboard_ga4_acquisition_daily (client_id, metric_date desc);
create index if not exists dashboard_ga4_acquisition_client_channel_idx
  on public.dashboard_ga4_acquisition_daily (client_id, channel_group, source_medium, metric_date desc);

alter table public.dashboard_ga4_acquisition_daily enable row level security;
drop policy if exists dashboard_ga4_acquisition_member_select on public.dashboard_ga4_acquisition_daily;
create policy dashboard_ga4_acquisition_member_select
  on public.dashboard_ga4_acquisition_daily
  for select to authenticated
  using ((select private.is_dashboard_client_member(client_id)));

revoke all on table public.dashboard_ga4_acquisition_daily from anon, authenticated;
grant select on table public.dashboard_ga4_acquisition_daily to authenticated;
grant all on table public.dashboard_ga4_acquisition_daily to service_role;
grant usage, select on sequence public.dashboard_ga4_acquisition_daily_id_seq to service_role;

create table if not exists public.dashboard_ga4_event_daily (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.dashboard_clients(id) on delete cascade,
  account_id text not null,
  metric_date date not null,
  event_name text not null,
  channel_group text not null,
  source_medium text not null,
  event_count bigint not null default 0 check (event_count >= 0),
  key_events numeric(20,6) not null default 0 check (key_events >= 0),
  ingested_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint dashboard_ga4_event_daily_unique
    unique (client_id, account_id, metric_date, event_name, channel_group, source_medium)
);

create index if not exists dashboard_ga4_event_client_date_idx
  on public.dashboard_ga4_event_daily (client_id, metric_date desc);
create index if not exists dashboard_ga4_event_client_name_date_idx
  on public.dashboard_ga4_event_daily (client_id, event_name, metric_date desc);
create index if not exists dashboard_ga4_event_client_source_date_idx
  on public.dashboard_ga4_event_daily (client_id, channel_group, source_medium, metric_date desc);

alter table public.dashboard_ga4_event_daily enable row level security;
drop policy if exists dashboard_ga4_event_member_select on public.dashboard_ga4_event_daily;
create policy dashboard_ga4_event_member_select
  on public.dashboard_ga4_event_daily
  for select to authenticated
  using ((select private.is_dashboard_client_member(client_id)));

revoke all on table public.dashboard_ga4_event_daily from anon, authenticated;
grant select on table public.dashboard_ga4_event_daily to authenticated;
grant all on table public.dashboard_ga4_event_daily to service_role;
grant usage, select on sequence public.dashboard_ga4_event_daily_id_seq to service_role;

create or replace function public.upsert_dashboard_ga4_acquisition_batch(
  p_client_slug text,
  p_account_id text,
  p_idempotency_key text,
  p_range_start date,
  p_range_end date,
  p_rows jsonb default '[]'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_client_id bigint;
  v_rows jsonb := coalesce(p_rows, '[]'::jsonb);
  v_row_count integer;
  v_existing public.dashboard_sync_runs%rowtype;
begin
  if p_range_start is null or p_range_end is null or p_range_start > p_range_end then
    raise exception 'invalid date range' using errcode = '22023';
  end if;
  if p_account_id is null or btrim(p_account_id) = '' then
    raise exception 'account id is required' using errcode = '22023';
  end if;
  if p_idempotency_key is null or length(btrim(p_idempotency_key)) not between 8 and 240 then
    raise exception 'invalid idempotency key' using errcode = '22023';
  end if;
  if jsonb_typeof(v_rows) <> 'array' or jsonb_array_length(v_rows) = 0 then
    raise exception 'acquisition batch cannot be empty' using errcode = '22023';
  end if;

  select dc.id into v_client_id
  from public.dashboard_clients dc
  where dc.slug = p_client_slug and dc.active;
  if v_client_id is null then
    raise exception 'dashboard client not found or inactive' using errcode = '22023';
  end if;

  select * into v_existing
  from public.dashboard_sync_runs dsr
  where dsr.client_id = v_client_id
    and dsr.source = 'ga4'
    and dsr.idempotency_key = p_idempotency_key;
  if found then
    return jsonb_build_object(
      'success', true, 'idempotent', true, 'dataset', 'acquisition',
      'rows', v_existing.daily_rows, 'range_start', v_existing.range_start,
      'range_end', v_existing.range_end
    );
  end if;

  if exists (
    select 1
    from jsonb_to_recordset(v_rows) as r(
      account_id text, metric_date date, channel_group text, source_medium text,
      sessions bigint, engaged_sessions bigint, new_users bigint,
      views bigint, events bigint, key_events numeric
    )
    where r.metric_date is null
       or r.metric_date < p_range_start or r.metric_date > p_range_end
       or r.channel_group is null or btrim(r.channel_group) = ''
       or r.source_medium is null or btrim(r.source_medium) = ''
       or (r.account_id is not null and r.account_id <> p_account_id)
       or coalesce(r.sessions,0) < 0 or coalesce(r.engaged_sessions,0) < 0
       or coalesce(r.new_users,0) < 0 or coalesce(r.views,0) < 0
       or coalesce(r.events,0) < 0 or coalesce(r.key_events,0) < 0
  ) then
    raise exception 'invalid acquisition row' using errcode = '22023';
  end if;

  delete from public.dashboard_ga4_acquisition_daily d
  where d.client_id = v_client_id
    and d.account_id = p_account_id
    and d.metric_date between p_range_start and p_range_end;

  insert into public.dashboard_ga4_acquisition_daily (
    client_id, account_id, metric_date, channel_group, source_medium,
    sessions, engaged_sessions, new_users, views, events, key_events
  )
  select
    v_client_id, p_account_id, r.metric_date, r.channel_group, r.source_medium,
    sum(coalesce(r.sessions,0))::bigint,
    sum(coalesce(r.engaged_sessions,0))::bigint,
    sum(coalesce(r.new_users,0))::bigint,
    sum(coalesce(r.views,0))::bigint,
    sum(coalesce(r.events,0))::bigint,
    sum(coalesce(r.key_events,0))::numeric(20,6)
  from jsonb_to_recordset(v_rows) as r(
    account_id text, metric_date date, channel_group text, source_medium text,
    sessions bigint, engaged_sessions bigint, new_users bigint,
    views bigint, events bigint, key_events numeric
  )
  group by r.metric_date, r.channel_group, r.source_medium;

  get diagnostics v_row_count = row_count;

  insert into public.dashboard_sync_runs (
    client_id, source, idempotency_key, range_start, range_end, status, daily_rows
  ) values (
    v_client_id, 'ga4', p_idempotency_key, p_range_start, p_range_end, 'success', v_row_count
  );

  return jsonb_build_object(
    'success', true, 'idempotent', false, 'dataset', 'acquisition',
    'rows', v_row_count, 'range_start', p_range_start, 'range_end', p_range_end
  );
end;
$function$;

revoke all on function public.upsert_dashboard_ga4_acquisition_batch(text,text,text,date,date,jsonb) from public, anon, authenticated;
grant execute on function public.upsert_dashboard_ga4_acquisition_batch(text,text,text,date,date,jsonb) to service_role;

create or replace function public.upsert_dashboard_ga4_event_batch(
  p_client_slug text,
  p_account_id text,
  p_idempotency_key text,
  p_range_start date,
  p_range_end date,
  p_rows jsonb default '[]'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_client_id bigint;
  v_rows jsonb := coalesce(p_rows, '[]'::jsonb);
  v_row_count integer;
  v_existing public.dashboard_sync_runs%rowtype;
begin
  if p_range_start is null or p_range_end is null or p_range_start > p_range_end then
    raise exception 'invalid date range' using errcode = '22023';
  end if;
  if p_account_id is null or btrim(p_account_id) = '' then
    raise exception 'account id is required' using errcode = '22023';
  end if;
  if p_idempotency_key is null or length(btrim(p_idempotency_key)) not between 8 and 240 then
    raise exception 'invalid idempotency key' using errcode = '22023';
  end if;
  if jsonb_typeof(v_rows) <> 'array' or jsonb_array_length(v_rows) = 0 then
    raise exception 'event batch cannot be empty' using errcode = '22023';
  end if;

  select dc.id into v_client_id
  from public.dashboard_clients dc
  where dc.slug = p_client_slug and dc.active;
  if v_client_id is null then
    raise exception 'dashboard client not found or inactive' using errcode = '22023';
  end if;

  select * into v_existing
  from public.dashboard_sync_runs dsr
  where dsr.client_id = v_client_id
    and dsr.source = 'ga4'
    and dsr.idempotency_key = p_idempotency_key;
  if found then
    return jsonb_build_object(
      'success', true, 'idempotent', true, 'dataset', 'events',
      'rows', v_existing.daily_rows, 'range_start', v_existing.range_start,
      'range_end', v_existing.range_end
    );
  end if;

  if exists (
    select 1
    from jsonb_to_recordset(v_rows) as r(
      account_id text, metric_date date, event_name text, channel_group text,
      source_medium text, event_count bigint, key_events numeric
    )
    where r.metric_date is null
       or r.metric_date < p_range_start or r.metric_date > p_range_end
       or r.event_name is null or btrim(r.event_name) = ''
       or r.channel_group is null or btrim(r.channel_group) = ''
       or r.source_medium is null or btrim(r.source_medium) = ''
       or (r.account_id is not null and r.account_id <> p_account_id)
       or coalesce(r.event_count,0) < 0 or coalesce(r.key_events,0) < 0
  ) then
    raise exception 'invalid event row' using errcode = '22023';
  end if;

  delete from public.dashboard_ga4_event_daily d
  where d.client_id = v_client_id
    and d.account_id = p_account_id
    and d.metric_date between p_range_start and p_range_end;

  insert into public.dashboard_ga4_event_daily (
    client_id, account_id, metric_date, event_name, channel_group, source_medium,
    event_count, key_events
  )
  select
    v_client_id, p_account_id, r.metric_date, r.event_name, r.channel_group, r.source_medium,
    sum(coalesce(r.event_count,0))::bigint,
    sum(coalesce(r.key_events,0))::numeric(20,6)
  from jsonb_to_recordset(v_rows) as r(
    account_id text, metric_date date, event_name text, channel_group text,
    source_medium text, event_count bigint, key_events numeric
  )
  group by r.metric_date, r.event_name, r.channel_group, r.source_medium;

  get diagnostics v_row_count = row_count;

  insert into public.dashboard_sync_runs (
    client_id, source, idempotency_key, range_start, range_end, status, daily_rows
  ) values (
    v_client_id, 'ga4', p_idempotency_key, p_range_start, p_range_end, 'success', v_row_count
  );

  return jsonb_build_object(
    'success', true, 'idempotent', false, 'dataset', 'events',
    'rows', v_row_count, 'range_start', p_range_start, 'range_end', p_range_end
  );
end;
$function$;

revoke all on function public.upsert_dashboard_ga4_event_batch(text,text,text,date,date,jsonb) from public, anon, authenticated;
grant execute on function public.upsert_dashboard_ga4_event_batch(text,text,text,date,date,jsonb) to service_role;

create or replace function public.get_dashboard_ga4_acquisition(
  p_client_slug text,
  p_start_date date,
  p_end_date date,
  p_limit integer default 10,
  p_cursor jsonb default null
)
returns jsonb
language plpgsql
stable
security invoker
set search_path = ''
as $function$
declare
  v_client_id bigint;
  v_limit integer;
  v_cursor_sessions numeric;
  v_cursor_channel text;
  v_cursor_source text;
  v_result jsonb;
begin
  if p_start_date is null or p_end_date is null or p_start_date > p_end_date then
    raise exception 'invalid date range' using errcode = '22023';
  end if;
  if p_end_date - p_start_date + 1 > 366 then
    raise exception 'date range cannot exceed 366 days' using errcode = '22023';
  end if;

  v_limit := least(greatest(coalesce(p_limit,10),1),100);
  v_cursor_sessions := nullif(p_cursor ->> 'sessions','')::numeric;
  v_cursor_channel := nullif(p_cursor ->> 'channel_group','');
  v_cursor_source := nullif(p_cursor ->> 'source_medium','');
  v_client_id := private.dashboard_read_client_id(p_client_slug);

  with acquisition as (
    select
      a.channel_group,
      a.source_medium,
      sum(a.sessions)::numeric as sessions,
      sum(a.engaged_sessions)::numeric as engaged_sessions,
      sum(a.new_users)::numeric as new_users,
      sum(a.views)::numeric as views,
      sum(a.events)::numeric as events,
      sum(a.key_events)::numeric as key_events
    from public.dashboard_ga4_acquisition_daily a
    where a.client_id=v_client_id and a.metric_date between p_start_date and p_end_date
    group by a.channel_group,a.source_medium
  ),
  leads as (
    select e.channel_group,e.source_medium,sum(e.event_count)::numeric as generate_leads
    from public.dashboard_ga4_event_daily e
    where e.client_id=v_client_id and e.metric_date between p_start_date and p_end_date
      and e.event_name='generate_lead'
    group by e.channel_group,e.source_medium
  ),
  enriched as (
    select
      a.channel_group,a.source_medium,a.sessions,a.engaged_sessions,a.new_users,a.views,a.events,a.key_events,
      coalesce(l.generate_leads,0)::numeric as generate_leads,
      a.engaged_sessions*100/nullif(a.sessions,0) as engagement_rate,
      coalesce(l.generate_leads,0)*100/nullif(a.sessions,0) as lead_rate
    from acquisition a
    left join leads l using(channel_group,source_medium)
  ),
  filtered as (
    select e.* from enriched e
    where v_cursor_sessions is null
       or e.sessions < v_cursor_sessions
       or (e.sessions = v_cursor_sessions and e.channel_group > v_cursor_channel)
       or (e.sessions = v_cursor_sessions and e.channel_group = v_cursor_channel and e.source_medium > v_cursor_source)
  ),
  limited as (
    select f.* from filtered f
    order by f.sessions desc,f.channel_group,f.source_medium
    limit v_limit+1
  ),
  visible as (
    select l.* from limited l
    order by l.sessions desc,l.channel_group,l.source_medium
    limit v_limit
  )
  select jsonb_build_object(
    'items',coalesce((select jsonb_agg(to_jsonb(v) order by v.sessions desc,v.channel_group,v.source_medium) from visible v),'[]'::jsonb),
    'total_count',(select count(*) from enriched),
    'next_cursor',case when (select count(*) from limited)>v_limit then (
      select jsonb_build_object('sessions',v.sessions,'channel_group',v.channel_group,'source_medium',v.source_medium)
      from visible v order by v.sessions asc,v.channel_group desc,v.source_medium desc limit 1
    ) else null end
  ) into v_result;

  return v_result;
end;
$function$;

revoke all on function public.get_dashboard_ga4_acquisition(text,date,date,integer,jsonb) from public, anon;
grant execute on function public.get_dashboard_ga4_acquisition(text,date,date,integer,jsonb) to authenticated, service_role;

create or replace function public.get_dashboard_ga4_events(
  p_client_slug text,
  p_start_date date,
  p_end_date date,
  p_limit integer default 10,
  p_cursor jsonb default null
)
returns jsonb
language plpgsql
stable
security invoker
set search_path = ''
as $function$
declare
  v_client_id bigint;
  v_limit integer;
  v_days integer;
  v_cursor_count numeric;
  v_cursor_name text;
  v_result jsonb;
begin
  if p_start_date is null or p_end_date is null or p_start_date > p_end_date then
    raise exception 'invalid date range' using errcode = '22023';
  end if;
  v_days := p_end_date-p_start_date+1;
  if v_days > 366 then
    raise exception 'date range cannot exceed 366 days' using errcode = '22023';
  end if;

  v_limit := least(greatest(coalesce(p_limit,10),1),100);
  v_cursor_count := nullif(p_cursor ->> 'event_count','')::numeric;
  v_cursor_name := nullif(p_cursor ->> 'event_name','');
  v_client_id := private.dashboard_read_client_id(p_client_slug);

  with aggregated as (
    select e.event_name,sum(e.event_count)::numeric as event_count,sum(e.key_events)::numeric as key_events
    from public.dashboard_ga4_event_daily e
    where e.client_id=v_client_id and e.metric_date between p_start_date and p_end_date
    group by e.event_name
  ),
  enriched as (
    select a.event_name,a.event_count,a.event_count/v_days::numeric as daily_average,a.key_events,
      a.event_count*100/nullif(sum(a.event_count) over(),0) as share_of_total
    from aggregated a
  ),
  filtered as (
    select e.* from enriched e
    where v_cursor_count is null
       or e.event_count < v_cursor_count
       or (e.event_count=v_cursor_count and e.event_name>v_cursor_name)
  ),
  limited as (
    select f.* from filtered f order by f.event_count desc,f.event_name limit v_limit+1
  ),
  visible as (
    select l.* from limited l order by l.event_count desc,l.event_name limit v_limit
  )
  select jsonb_build_object(
    'items',coalesce((select jsonb_agg(to_jsonb(v) order by v.event_count desc,v.event_name) from visible v),'[]'::jsonb),
    'total_count',(select count(*) from enriched),
    'next_cursor',case when (select count(*) from limited)>v_limit then (
      select jsonb_build_object('event_count',v.event_count,'event_name',v.event_name)
      from visible v order by v.event_count asc,v.event_name desc limit 1
    ) else null end
  ) into v_result;

  return v_result;
end;
$function$;

revoke all on function public.get_dashboard_ga4_events(text,date,date,integer,jsonb) from public, anon;
grant execute on function public.get_dashboard_ga4_events(text,date,date,integer,jsonb) to authenticated, service_role;
;
